name: puma
channels:
  - conda-forge
dependencies:
  - python

  # pumapy
  - numpy
  - scikit-image
  - scipy=1.11
  - matplotlib 
  - pyvista

  # puma cpp
  - fftw
  - eigen
  - openmp
  - cmake 

  # puma gui
  - qt

  # texgen
  - swig

  # nice to have
  - pip
  - cython
  - scikit-umfpack
  - jupyterlab
  - ipyvtklink
  - ipympl
