name: Doc-Test pumapy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]  # ubuntu-latest, windows-latest,
        python-version: ['3.9']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          conda create -y --name puma -c conda-forge puma pytest
          conda init bash
          source ~/.bash_profile
          conda activate puma
          python -m pip install --upgrade pip
          python -m  pip install -e .
      - name: Test with doctest
        working-directory: .
        run: |
          conda init bash
          source ~/.bash_profile
          conda activate puma
          python -m doctest -o=ELLIPSIS -o=NORMALIZE_WHITESPACE python/pumapy/*/*.py
