name: Test pumapy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # macos-latest, windows-latest,
        python-version: ['3.9']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install libgl1 -y
          conda create -y --name puma -c conda-forge puma gcc pytest
          conda init bash
          source ~/.bashrc
          conda activate puma
          python -m pip install --upgrade pip
          python -m  pip install -e .
          python -c "import pumapy"
      - name: Test with pytest
        working-directory: ./python/test
        run: |
          conda init bash
          source ~/.bashrc
          conda activate puma
          pytest
